/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutRouteImport } from './routes/workout'
import { Route as ShareReceiverRouteImport } from './routes/share-receiver'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DayDayRouteImport } from './routes/day.$day'
import { Route as CustomNewRouteImport } from './routes/custom.new'
import { Route as CustomIdEditRouteImport } from './routes/custom.$id.edit'

const WorkoutRoute = WorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareReceiverRoute = ShareReceiverRouteImport.update({
  id: '/share-receiver',
  path: '/share-receiver',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DayDayRoute = DayDayRouteImport.update({
  id: '/day/$day',
  path: '/day/$day',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomNewRoute = CustomNewRouteImport.update({
  id: '/custom/new',
  path: '/custom/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomIdEditRoute = CustomIdEditRouteImport.update({
  id: '/custom/$id/edit',
  path: '/custom/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/nutrition': typeof NutritionRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/share-receiver': typeof ShareReceiverRoute
  '/workout': typeof WorkoutRoute
  '/custom/new': typeof CustomNewRoute
  '/day/$day': typeof DayDayRoute
  '/custom/$id/edit': typeof CustomIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/nutrition': typeof NutritionRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/share-receiver': typeof ShareReceiverRoute
  '/workout': typeof WorkoutRoute
  '/custom/new': typeof CustomNewRoute
  '/day/$day': typeof DayDayRoute
  '/custom/$id/edit': typeof CustomIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/nutrition': typeof NutritionRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/share-receiver': typeof ShareReceiverRoute
  '/workout': typeof WorkoutRoute
  '/custom/new': typeof CustomNewRoute
  '/day/$day': typeof DayDayRoute
  '/custom/$id/edit': typeof CustomIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/nutrition'
    | '/progress'
    | '/settings'
    | '/share-receiver'
    | '/workout'
    | '/custom/new'
    | '/day/$day'
    | '/custom/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/nutrition'
    | '/progress'
    | '/settings'
    | '/share-receiver'
    | '/workout'
    | '/custom/new'
    | '/day/$day'
    | '/custom/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/nutrition'
    | '/progress'
    | '/settings'
    | '/share-receiver'
    | '/workout'
    | '/custom/new'
    | '/day/$day'
    | '/custom/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  NutritionRoute: typeof NutritionRoute
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  ShareReceiverRoute: typeof ShareReceiverRoute
  WorkoutRoute: typeof WorkoutRoute
  CustomNewRoute: typeof CustomNewRoute
  DayDayRoute: typeof DayDayRoute
  CustomIdEditRoute: typeof CustomIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-receiver': {
      id: '/share-receiver'
      path: '/share-receiver'
      fullPath: '/share-receiver'
      preLoaderRoute: typeof ShareReceiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day/$day': {
      id: '/day/$day'
      path: '/day/$day'
      fullPath: '/day/$day'
      preLoaderRoute: typeof DayDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom/new': {
      id: '/custom/new'
      path: '/custom/new'
      fullPath: '/custom/new'
      preLoaderRoute: typeof CustomNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom/$id/edit': {
      id: '/custom/$id/edit'
      path: '/custom/$id/edit'
      fullPath: '/custom/$id/edit'
      preLoaderRoute: typeof CustomIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  NutritionRoute: NutritionRoute,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  ShareReceiverRoute: ShareReceiverRoute,
  WorkoutRoute: WorkoutRoute,
  CustomNewRoute: CustomNewRoute,
  DayDayRoute: DayDayRoute,
  CustomIdEditRoute: CustomIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
